name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  go-version: "1.23.x"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.go-version }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles ('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      run: |
        task test

  lint:
    name: Lint 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.go-version }}
        cache: false
    - name: Lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: latest
        args: -c .golangci.yml
  